# Generated by Django 6.0.7 on 2026-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=6)),
                ('qualification', models.TextField(max_length=100)),
                ('dob', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
